### ISSUE TITLE
Some image inside newly created folder that has image won't show up

### ISSUE THREAD

**Issue by muhrifqii** [DroidNinja/Android-FilePicker#102]
even there is no .nomedia file, it won't show up on image picker

**Comment by DroidNinja** [comment]
FilePicker shows images from MediaStore database. If there is no entry for that folder yet, then it wont show. What code are using?

**Comment by muhrifqii** [comment]
This is the FilePickerBuilder code

`FilePickerBuilder.getInstance().setMaxCount(1).showGifs(false)
              .enableVideoPicker(true)
              .enableCameraSupport(false)
              //.setSelectedFiles(pathList)
              .setActivityTheme(R.style.PickerTheme).pickPhoto(this);`

previously the newly created folder showed on the list nicely. and then when the folder is removed and re-created again with pictures inside it, the folder won't show up on the list

**Comment by mustafa-demir** [comment]
Same problem here. I added support for m3u files. It showed one firstly. And then I created some other files with the same type, but file picker didn't show them until I restarted emulator. So it is a big problem that needs to be resolved.

**Comment by DroidNinja** [comment]
If you try to put an entry to mediastore manually, It might make duplicate entries on some devices. I have tried to make an entry to the mediastore database while taking photos from the camera. But for some devices, it showed duplicate entries for the captured photo.

**Comment by muhrifqii** [comment]
@DroidNinja Is there a better way for doing so? Because in my case, there are images downloaded from the web as array of bytes and then save it

**Comment by GremlinsInGame** [comment]
I seem to be dealing with this issue as well.
My App creates files of type .CSV.   I initally thought that it wasnt finding them because of what folder they reside in.  But it seems as though the MediaStore doesnt pick up the file until it gets modified in some way outside of my app.  I can rename or move with File Manager for instance and then Filepicker will start seeing it. 
Anyone know how to force Android Mediastore to update with my file so that FilePicker will see it?

**Comment by uscmsr** [comment]
Just manually add your new file to MediaStore and you will be able to see it. Here's how:
https://stackoverflow.com/questions/3300137/how-can-i-refresh-mediastore-on-android

**Comment by DroidNinja** [comment]
Also checkout `notifyMediaStore(Context context, String path` method in `FilePickerUtils` to notify MediaStore to update its entry. It will first check if its already exists to check duplicate entries.
