### ISSUE TITLE
 onActivityResult() not executed after selecting images in fragment

### ISSUE THREAD

**Issue by naiksan** [DroidNinja/Android-FilePicker#105]
**Inside fragment I call using this below code.**
                                FilePickerBuilder.getInstance().setMaxCount(4)
                                        .setSelectedFiles(null)
                                        .setActivityTheme(R.style.AppTheme)
                                        .enableImagePicker(true)
                                        .pickPhoto(getActivity());
**My onActivityResult()**
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        Log.d(TAG, "path1: " + lastImagePath);
        if (resultCode == RESULT_OK) {
            if (requestCode == FilePickerConst.REQUEST_CODE_PHOTO) {
                ArrayList<String> newPath = new ArrayList<>();
                newPath.addAll(data.getStringArrayListExtra(FilePickerConst.KEY_SELECTED_MEDIA));
                Log.d(TAG,"paths: " + newPath);
                saveImage(newPath.get(0));

            } .......
......
.....

**Comment by DroidNinja** [comment]
You need to use `.pickPhoto(this)` in fragment instead of `.pickPhoto(getActivity());` as it will call activity's `onActivityResult` method.

**Comment by naiksan** [comment]
I've used .pickPhoto(FragName.this)
worked for me, thanks though.
