### ISSUE TITLE
Search with a long time

### ISSUE THREAD

**Issue by CB-ysx** [DroidNinja/Android-FilePicker#110]
If it's a lot of files in the phone, it will search file for a long time.

**Comment by DroidNinja** [comment]
Yeah thats the thing, It will get all files data from Mediastore database and then categorises into different extensions you specified. and this might take time.

**Comment by RabieMohimane** [comment]
how to show a loader/progress when searching for files? is there any callbacks for start searching and when searching finished?

**Comment by DroidNinja** [comment]
There is already loader while searching for files.
