### ISSUE TITLE
Conflict with .asBitmap() Glide v4.0

### ISSUE THREAD

**Issue by putrapurba** [DroidNinja/Android-FilePicker#111]
Hi there, 

I got this error when build the project, are you override GlideAnimation class?

`Error:(8, 44) error: package com.bumptech.glide.request.animation does not exist`

**Comment by DroidNinja** [comment]
Are you sure because current sample project is building just fine? and that `com.bumptech.glide.request.animation` class is not even used anywhere in the project.

**Comment by putrapurba** [comment]
After update my android studio this issue resolved but got another issue when pick image, o cmon I really love the design :(
