### ISSUE TITLE
Didn't find class "droidninja compile 'com.droidninja:filepicker:2.0.8'

### ISSUE THREAD

**Issue by hpivarni** [DroidNinja/Android-FilePicker#112]
java.lang.RuntimeException: Unable to get provider droidninja.filepicker.utils.FilePickerProvider: java.lang.ClassNotFoundException: Didn't find class "droidninja

and in manifest 
      <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.varni.professionalresumemamker"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>

**Comment by DroidNinja** [comment]
Rebuild and compile. Just released new version.

**Comment by marconealberto** [comment]
I still get this error with 2.1.2 on some devices:

java.lang.RuntimeException: Unable to get provider droidninja.filepicker.utils.FilePickerProvider: java.lang.ClassNotFoundException: Didn't find class "droidninja.filepicker.utils.FilePickerProvider
