### ISSUE TITLE
Nothing happens when setMaxCount is set to 1

### ISSUE THREAD

**Issue by marconealberto** [DroidNinja/Android-FilePicker#113]
The Activity is not launched, and the problem goes away if I set it to a different number.

**Comment by Alb93** [comment]
Also for me: new activity starts and immediately closes without any stack trace or log.

My code: `String[] pdfTypes = {".pdf"};
        String[] txtTypes = {".txt"};
        String[] wordTypes = {".doc", ".word"};
        FilePickerBuilder.getInstance().setMaxCount(1)
                .enableDocSupport(false)
                .addFileSupport("TXT",txtTypes, R.drawable.txt)
                .addFileSupport("PDF",pdfTypes, R.drawable.pdf)
                .addFileSupport("WORD",wordTypes, R.drawable.word)
                .setActivityTheme(R.style.AppTheme)
                .pickFile(this);`

Please fix :)

**Comment by zackpollard** [comment]
I am also experiencing this behaviour, it fails whenever setMaxCount is 1.

**Comment by DroidNinja** [comment]
Thanks for reporting. Fixed in 2.1.0

**Comment by RuslanKham322** [comment]
Same problem with media picking.
`MediaDetailsActivity`:
`onCreateOptionsMenu` calls `onItemSelected()`. In this method:
```java
...
if(maxCount==1) {
    setResult(RESULT_OK, null);
    finish();
}
...
```

**Comment by mrgames13** [comment]
I also ran into this problem. App crashes when clicking on one folder.

**Comment by ipodib** [comment]
The issue is not fixed in 2.1.0.  I see the same problem. And according to @RuslanKham322 reason is simple: library returns nothing when maxCount is 1.

**Comment by forming** [comment]
The issue still present.

**Comment by CallumCoombes** [comment]
Yeah, this is still an issue. Not crashing, just cannot enter folders containing images making it unusable.

**Comment by ipodib** [comment]
Everyone who needs a workaround for this bug can revert to 2.0.8 version. This version does not have this bug.

**Comment by CallumCoombes** [comment]
Tested reverting to 2.0.8 and you are correct.

**Comment by DroidNinja** [comment]
Hey g

**Comment by DroidNinja** [comment]
Hey guys could you verify if its fixed ? Last version was really a mess. Sorry :/

**Comment by forming** [comment]
Just checked and it seems to be working on 2.1.1 version. Thanks!
