### ISSUE TITLE
Not able to pick files from root directory of Internal Storage

### ISSUE THREAD

**Issue by sreejithbnaick** [DroidNinja/Android-FilePicker#119]
For example:
File in /sdcard/test.txt (A file in root internal storage) is not recognized, until it is moved to some folder, /sdcard/test/test.txt

**Comment by gufengpiaoyi** [comment]
I have the same problem.It's also ok if  it's renamed.

**Comment by shaik305** [comment]
how did you manage to get opened internal sdcard

**Comment by SAYEDALISINA93** [comment]
I cant get the path file any idea what is the problem???

**Comment by DroidNinja** [comment]
Its because It does not have entry in MediaStore database. There is method in FilePickerUtils class named notifyMediaStore(Context context, String path) through which you can notify the MediaStore database.

**Comment by kalyanramAdiraju** [comment]
How do I get access to FilePickerUtils class?

**Comment by kalyanramAdiraju** [comment]
I have downloaded a file from chrome and renamed it the picker is not reflecting the renamed file but it showing the name of the previous file. please help me!!

**Comment by kalyanramAdiraju** [comment]
I have downloaded a file from chrome and renamed it the picker is not reflecting the renamed file but it showing the name of the previous file. please help me!!

**Comment by DroidNinja** [comment]
@kalyanramAdiraju If you are renaming the file in from Downloads app, then I guess that will not work. Because in the AOSP code, renaming in downloads only works for images not for other files. I know this is an issue. You can file bug at their repo.
See this code for reference: https://github.com/aosp-mirror/platform_frameworks_base/blob/d18ed49f9dba09b85782c83999a9103dec015bf2/core/java/android/app/DownloadManager.java#L1255

**Comment by Devendra-Shrooms** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bluetie/droidninja.filepicker.FilePickerActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
