### ISSUE TITLE
Is it possible to combine photo and document Pocker together?

### ISSUE THREAD

**Issue by e-verdillon** [DroidNinja/Android-FilePicker#12]
Hi,

Can we use the potoPicker and the documentpicker together.
For exemple: max file: 10 
10 photos and 0 doc or 7photos and 3 docs etc...

Resgards

**Comment by DroidNinja** [comment]
Yes its possible. You need to apply some business logic for doing this. Even I modified this library for this particular use in a project m working on. I will update the library for soon.

**Comment by e-verdillon** [comment]
Great !

Best regards from French Alps

**Comment by DroidNinja** [comment]
@e-verdillon I have modified library to be used as combined document and photo picker. Please check and let me know if you find any issue. Thanks!
