### ISSUE TITLE
Permission Denial Issue on unofficial case.

### ISSUE THREAD

**Issue by jayesh28589** [DroidNinja/Android-FilePicker#123]
Hello,

I have found one unofficial issue in filepicker.

Let's follow this steps.
Device: Samsung galaxy J3 - Android Nougat
1. Open the filepicker
2. Allow both camera and storage permission
3. Open any folder (i.e All Images)
4. At the same time go to app settings and disable both permission
5. come back to app.

App will crash.

> FATAL EXCEPTION: ModernAsyncTask #2
>                                                    Process: com.pasl, PID: 12144
>                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
>                                                        at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
>                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                        at java.lang.Thread.run(Thread.java:762)
>                                                     Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=12144, uid=10394 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
>                                                        at android.os.Parcel.readException(Parcel.java:1693)
>                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
>                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
>                                                        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
>                                                        at android.content.ContentResolver.query(ContentResolver.java:536)
>                                                        at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
>                                                        at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
>                                                        at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
>                                                        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
>                                                        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
>                                                        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
>                                                        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
>                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
>                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
>                                                        at java.lang.Thread.run(Thread.java:762) 
> 

Thanks.

**Comment by DroidNinja** [comment]
Fixed in 2.1.2. Thanks for reporting.

**Comment by pouriabagheri** [comment]
Still Facing the same issue

**Comment by jerinamathews** [comment]
Still facing this issue
