### ISSUE TITLE
its not working on galaxy s5 

### ISSUE THREAD

**Issue by Pradeep0801** [DroidNinja/Android-FilePicker#125]
in galaxy s5 it comes with blank screen and videos are not loaded .
S5 uses google photos app for showing video and photos.

**Comment by edisonthk** [comment]
I have same issue too. Photo stored in local media are showing but Google Photo are not.

**Comment by Pradeep0801** [comment]
@edisonthk is there any solution for this?
How can we load files which are not in local storage?

**Comment by DroidNinja** [comment]
This library only list files and photos which are locally on device. For google photos, you need to explicitly set intent to select google photos app. Search stackoverflow for this.
