### ISSUE TITLE
Show Loader when searching for files 

### ISSUE THREAD

**Issue by RabieMohimane** [DroidNinja/Android-FilePicker#126]
how to show a loader/progress when searching for files? is there any callbacks for start searching and when searching finished?

**Comment by RabieMohimane** [comment]
and please how to change the check mark color and background

**Comment by DroidNinja** [comment]
Loader is already configured for file picker. You can check styling section in readme to change checkmark color and background.

**Comment by RabieMohimane** [comment]
i can't change the check color:
![sans titre](https://user-images.githubusercontent.com/12934546/36112206-c728e768-1020-11e8-8b10-1ea98a2fa67f.png)
