### ISSUE TITLE
Add an option to set file picker activity toolbar title

### ISSUE THREAD

**Issue by MrSurana** [DroidNinja/Android-FilePicker#128]
An option in builder to set custom title to the file picker activity.

**Comment by MauriPastorini** [comment]
I have the same concern, is it possible? Or to change the language.

**Comment by MrSurana** [comment]
I have created a pull request #129 with a fix for this. Waiting for it to be merged.

**Comment by DroidNinja** [comment]
@MrSurana Thanks for the pull request. Merged it. Will release a new version soon.

**Comment by MauriPastorini** [comment]
@MrSurana Great! Is it possible to change title and the "done"  text option?
