### ISSUE TITLE
No camera support when no picture in gallery

### ISSUE THREAD

**Issue by fjr619** [DroidNinja/Android-FilePicker#138]
I have a problem so in my gallery there is no photos, and already set enableCameraSupport = true, but i can't find how to open camera with this. It will not have a problem if I have at least 1 images in my devices.

This is the result when there no image, so the icon to open camera is not appear
![screenshot_2018-02-23-13-58-15](https://user-images.githubusercontent.com/9444636/36581950-f7e31cd2-18a1-11e8-8e12-195f231629af.png)

This is when there are images, ithe icon to open camera is appear
![screenshot_2018-02-23-13-56-01](https://user-images.githubusercontent.com/9444636/36581919-dbd6f9a0-18a1-11e8-970d-20580b8c2ddd.png)

So how to make camera icon is appear when there is no image in devices?

**Comment by Argonisius** [comment]
I have the same issue. Running Android 8.0.0 in emulator.

**Comment by DroidNinja** [comment]
Try 2.1.5. Tested on emulator api 25.
