### ISSUE TITLE
Pick a folder

### ISSUE THREAD

**Issue by royale1223** [DroidNinja/Android-FilePicker#14]
It would be useful to have an api to pick a folder.

**Comment by DroidNinja** [comment]
Ok, I will try add folder view in upcoming version.

**Comment by ankurt-optimus** [comment]
i might implement the file explorer on this, much needed enhancement, nice work overall. And support and google drive and other document providers would be nice to have too.

**Comment by kashifo** [comment]
@DroidNinja Can i add this feature?

**Comment by DroidNinja** [comment]
@kashifo Yeah sure! no problem.

**Comment by DroidNinja** [comment]
done
