### ISSUE TITLE
Video Picker Issue 

### ISSUE THREAD

**Issue by ramupal2613** [DroidNinja/Android-FilePicker#142]
When I want to use photo and video picker both in same activity but for different method how to differentiate file picked  is image or video?

**Comment by mghisham** [comment]
@ramupal2613 Try this.

`
public static boolean isVideoFile(String fileUrl) {
    String mimeType = getMimeType(fileUrl);
    return isVideo(mimeType);
}
public static String getMimeType(String fileUrl) {
    String extension = MimeTypeMap.getFileExtensionFromUrl(fileUrl);
    return MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
}
public static boolean isVideo(String mimeType) {
    return mimeType != null && mimeType.startsWith("video");
}
public static boolean isImage(String mimeType) {
    return mimeType != null && mimeType.startsWith("image");
}
`

**Comment by ramupal2613** [comment]
ok thanks will check and i think it is better to add support customize request code to overcome this type of problem and no need to check file type every time.
