### ISSUE TITLE
Toolbar search does not accept uppercase characters.

### ISSUE THREAD

**Issue by ninogonzales** [DroidNinja/Android-FilePicker#144]
If I have a file called "My File.txt", if I type 'M' on the search bar, the file will not appear. But if I type 'm', it will be displayed correctly. 

Also, is there a way to disable the toolbar completely?

Thanks,
Nino

**Comment by DroidNinja** [comment]
Search is working at my end. I tried with app sample project. You cannot disabled the toolbar as it is a way to select and return to your app.

**Comment by DroidNinja** [comment]
fixed. Check 2.1.5
