### ISSUE TITLE
After adding your library depending I can not assemble the project

### ISSUE THREAD

**Issue by PikselNsk** [DroidNinja/Android-FilePicker#145]
Hello! After adding your library depending I can not assemble the project! What could be the reason?
![image](https://user-images.githubusercontent.com/8215286/36848560-a42d4ae2-1d72-11e8-8cc9-390a6b55a550.png)

**Comment by DroidNinja** [comment]
Thats weird...have you tried clean and rebuild?

**Comment by PikselNsk** [comment]
Of course. Many times =( Does it matter which theme is used in the application?

**Comment by DroidNinja** [comment]
I think it could be appcompat issue as filepicker is using `27.0.2` version. Could you try updating your support libraries?

**Comment by PikselNsk** [comment]
![image](https://user-images.githubusercontent.com/8215286/36852156-13d04d5a-1d7c-11e8-8660-0a20d93a9485.png)
The same ... I really want to use your library =(

**Comment by PikselNsk** [comment]
My gradle file 
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "info.javaway.soundsforsleeping"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile 'com.jakewharton:butterknife:8.8.1'
    compile 'com.jakewharton:butterknife-compiler:8.8.1'
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.3'
    compile 'com.github.warkiz.widget:indicatorseekbar:1.1.2'
    compile 'com.droidninja:filepicker:2.1.3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}
`

**Comment by DroidNinja** [comment]
Can you post your `style.xml`?

**Comment by PikselNsk** [comment]
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>
    
    <style name="ContainerTextMainScreen">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:layout_margin">4dp</item>
        <item name="android:background">@drawable/bckg_container</item>
    </style>

    <style name="CardText">
        <item name="android:textColor">@android:color/white</item>
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:padding">16dp</item>
        <item name="android:layout_margin">16dp</item>
        <item name="android:textSize">32dp</item>
        <item name="android:background">@drawable/text_bckg</item>
    </style>

    <style name="ActionContainer">
        <item name="android:background">@drawable/bckg_action_dark_trans</item>
        <item name="android:layout_width">@dimen/sub_sound_image_view</item>
        <item name="android:layout_height">@dimen/sub_sound_image_view</item>
        <item name="android:layout_margin">8dp</item>
        <item name="android:gravity">center</item>
        <item name="android:orientation">vertical</item>
    </style>

    <style name="SubSoundImageView">
        <item name="android:layout_width">@dimen/sub_sound_image_view</item>
        <item name="android:layout_height">@dimen/sub_sound_image_view</item>
        <item name="android:layout_margin">@dimen/sub_sound_image_view_margin</item>
    </style>

</resources>

```

**Comment by DroidNinja** [comment]
That is really really weird. Everything is all right. I know its unneccessary but could try to add `compile 'com.android.support:support-v4:27.0.2'` to your app module and see if it works?

**Comment by PikselNsk** [comment]
```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile 'com.android.support:support-v4:27.0.2'
    compile 'com.jakewharton:butterknife:8.8.1'
    compile 'com.jakewharton:butterknife-compiler:8.8.1'
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.3'
    compile 'com.github.warkiz.widget:indicatorseekbar:1.1.2'
    compile 'com.droidninja:filepicker:2.1.3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}
```
![image](https://user-images.githubusercontent.com/8215286/36853603-f625a972-1d7f-11e8-8e1f-5350592d8d13.png)

**Comment by PikselNsk** [comment]
I'll try to fix a mistake tomorrow with a fresh head ...

**Comment by DroidNinja** [comment]
@PikselNsk I am sorry...it was `com.android.support:design:27.0.2`. i updated the comment. I am suggesting this because tablayout belongs to the design support module.

**Comment by PikselNsk** [comment]
@DroidNinja  Yes! Now everything works! Thank you, you're gorgeous! From me a movie! =)
