### ISSUE TITLE
Compatibility with newer support libraries (27)

### ISSUE THREAD

**Issue by jxie93** [DroidNinja/Android-FilePicker#150]
When I updated my android support libraries to version 27 and above I found a issue with the picker while using it for video and image. 

I open a folder (eg. camera), and then when I return to the top level directory, the picker shows no files found.

I forced my app to build with 26.1.0 support libraries in my gradle file and everything worked fine again.

**Comment by iamchurchill** [comment]
Thanks for the library. please can you kindly work on removing the done button when the maximum possible item to select is 1 and i get black activity when i move back from one step from the folder view to the main filepicker activity. Thanks again.

**Comment by DroidNinja** [comment]
fixed in 2.1.4
