### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;

### ISSUE THREAD

**Issue by webserveis** [DroidNinja/Android-FilePicker#151]

**Comment by DroidNinja** [comment]
This is glide issue and have been raised many times. I have updated Glide to latest version in 2.1.4. Try it.

**Comment by borosuman** [comment]
@DroidNinja I am facing same issue on the latest version 2.1.4

**Comment by jitarun** [comment]
@DroidNinja also facing same issue on v2.1.5. please help

**Comment by borosuman** [comment]
@jitarun  I solved this issue by adding the following line inside dependencies section of build.gradle
 `implementation 'com.github.bumptech.glide:glide:4.7.1'`
