### ISSUE TITLE
When I choose nothing,I click DONE button,App crash.

### ISSUE THREAD

**Issue by handsonpig** [DroidNinja/Android-FilePicker#159]
When I choose nothing,I click DONE button,App crash.

**Comment by handsonpig** [comment]
FilePickerBuilder.getInstance().setMaxCount(1)
                        .setSelectedFiles(filepaths)
                        .setActivityTheme(R.style.LibAppTheme)
                        .pickDocument(this);

When I open "Select a document" activity ,if I do not choose any  item from the ListView in this activity,then click the "DONE" button,app will crash.

logcat has these warm:
E/Preprocessor: ***ATTENTION*** preloadInner failed: 
E/Preprocessor: ***ATTENTION*** preloadInner failed: android.webview.chromium.WebViewChromiumFactoryProvider$5com.tencent.tbs.core.webkit.tencent.TencentWebViewProxy$9
E/Preprocessor: ***ATTENTION*** preloadInner failed: com.tencent.tbs.core.webkit.WebView$2
E/Preprocessor: ***ATTENTION*** preloadInner failed: com.tencent.smtt.webkit.WebViewChromiumExtension$49

I think these error has nothing to do with this issue

**Comment by DroidNinja** [comment]
@handsonpig  but done button does not show up until you select atleast one item.

**Comment by handsonpig** [comment]
@DroidNinja  I am sorry,I used the old version 1.0.6 before ,now I hava changed it to the latest version，everything works fine.thank you!!your library is very nice.
