### ISSUE TITLE
java.lang.NoSuchFieldError: No static field transparent_bg of type I in class Ldroidninja/filepicker/R$id; or its superclasses (declaration of 'droidninja.filepicker.R$id'

### ISSUE THREAD

**Issue by hnyer** [DroidNinja/Android-FilePicker#16]
![image](https://cloud.githubusercontent.com/assets/5989755/19258531/15397cc6-8fab-11e6-8d06-07704c3ca154.png)

**Comment by DroidNinja** [comment]
weird issue...Did you try to clean and build your project again?

**Comment by Archinamon** [comment]
I've got the same error. Maybe it conflicts with any libraries? I'd suggest to use a lib namespace prefix to all R.* identifiers to avoid such errors.
