### ISSUE TITLE
onResultCallback will be called twice when take a photograph back to picker view

### ISSUE THREAD

**Issue by fishwjy** [DroidNinja/Android-FilePicker#17]
Actually, I think this may not your code's bug. I found the callback onLoadFinished() in LoaderManager.LoaderCallbacks will be called twice when take a photo then back to pick view. That leads to your own callback will be called twice.
So is that the google's bug? Do you have some opinion on this? Thanks a lot.

**Comment by DroidNinja** [comment]
Yes, It queries the database again for showing the image you captured from camera recently.
