### ISSUE TITLE
 Failed to process resources, see aapt output above for details.

### ISSUE THREAD

**Issue by Jay-YaoJie** [DroidNinja/Android-FilePicker#189]
AGPBI: {"kind":"error","text":"error: attribute \u0027com.xc.app:autoSizeMinTextSize\u0027 not found.","sources":[{"file":"C:\\Users\\yaoji\\.gradle\\caches\\transforms-1\\files-1.1\\filepicker-2.1.5.aar\\cc09df0ed1d2cd89bbef53b6dc4b91b3\\res\\layout\\item_doc_layout.xml","position":{"startLine":17}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.xc.app:autoSizeStepGranularity\u0027 not found.","sources":[{"file":"C:\\Users\\yaoji\\.gradle\\caches\\transforms-1\\files-1.1\\filepicker-2.1.5.aar\\cc09df0ed1d2cd89bbef53b6dc4b91b3\\res\\layout\\item_doc_layout.xml","position":{"startLine":17}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: attribute \u0027com.xc.app:autoSizeTextType\u0027 not found.","sources":[{"file":"C:\\Users\\yaoji\\.gradle\\caches\\transforms-1\\files-1.1\\filepicker-2.1.5.aar\\cc09df0ed1d2cd89bbef53b6dc4b91b3\\res\\layout\\item_doc_layout.xml","position":{"startLine":17}}],"original":"","tool":"AAPT"}

The specified Android SDK Build Tools version (25.0.3)   Android Gradle Plugin 3.1.4.

**Comment by Zeoye** [comment]
I have the same problem

**Comment by developerashish01** [comment]
any solution there?

**Comment by Zeoye** [comment]
> any solution there?

maybe  you have some bug in your  xml files,it's so long ,i had forget it.

**Comment by Jay-YaoJie** [comment]
https://gitee.com/MT5/GSApp   
Use project here, now modified good   。you can see
