### ISSUE TITLE
On custom toolbar done button not show

### ISSUE THREAD

**Issue by inceptiveDipak** [DroidNinja/Android-FilePicker#2]
Hello @DroidNinja,
Thanks for great lib for file picker.
I am using it in my android app for image picking. In my app there is custom toolbar with NoActionbar style it will not show me action bar in attachment activity. Is there any option for custom toolbar, show the done button within.

**Comment by DroidNinja** [comment]
If you are setting activity theme through  _.setActivityTheme()_  method, then you need to set a style with Actionbar as FilePickerActivity is built with DarkActionBar theme, like this:
``` xml
 <style name="FilePickerTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:colorForeground">@color/foreground_material_light</item>
        <item name="android:textColorPrimary">@android:color/black</item>
        <item name="android:textColorPrimaryInverse">@android:color/primary_text_light</item>
        <item name="android:windowBackground">@color/white</item>
        <item name="android:itemTextAppearance">@style/AndroidSRC.TextAppearance</item>
        <item name="android:itemBackground">@color/white</item>
    </style>
```

**Comment by inceptiveDipak** [comment]
Hey @DroidNinja thanks for reply,
I am not using the setActivityTheme in my any class.
There is my parent style like
`<style name="AppTheme" parent="Theme.AppCompat.Light. NoActionBar"> </style>`
And i have custom layout for toolbar which i insert and setSupportedActionbar() it in my activities.
In one of my activity there is button which start activity for filepicker at that time there is not present the in FilePickerActivity, so that i don't get any button over it.
Please help me.
Thank you !!

**Comment by DroidNinja** [comment]
Dude, you have to set theme for FilePickerActivity which has a parent of Theme.AppCompat.Light.DarkActionBar.

On your onclick method:
```java
  FilePickerBuilder.getInstance().setMaxCount(5)
                .setActivityTheme(R.style.FilePickerTheme)
                .pickPhoto(this);
```
Here FilePickerTheme is the style I mentioned in above post. Just remember you have to set Appcompat Actionbartheme for using FilePicker

**Comment by inceptiveDipak** [comment]
Ok got it, Thank you very much..

**Comment by DroidNinja** [comment]
I hope that problem is resolved now. :)
