### ISSUE TITLE
UpperCase file names.

### ISSUE THREAD

**Issue by bubkin** [DroidNinja/Android-FilePicker#21]
Hi, in not quite sure how should i marge into your files. 
But i found interesting problem, some devices use uppercase names in files.
So i think you should change
Utils class function:
public static boolean contains(String[] types, String path) {
        for (String string : types) {
            if (path.endsWith(string)) return true;
        }
        return false;
    }
into 
public static boolean contains(String[] types, String path) {
        for (String string : types) {
            if (path.toLowerCase().endsWith(string)) return true;
        }
        return false;
    }

**Comment by DroidNinja** [comment]
Thanks for suggesting this, adding to the latest build.
