### ISSUE TITLE
pickFile appears error

### ISSUE THREAD

**Issue by Sunedge** [DroidNinja/Android-FilePicker#218]
Hello 
I'm using com.droidninja:filepicker:2.2.0 and 
if I use like below (pickFile)
 FilePickerBuilder.Companion.getInstance().setMaxCount(5)
                        .setSelectedFiles(filePaths)
                        .setActivityTheme(R.style.AppTheme)
                        .pickFile(FileFragment.this);

appears error 
java.lang.RuntimeException: Unable to start activity ComponentInfo{uz.baholash/droidninja.filepicker.FilePickerActivity}: java.lang.IllegalStateException: PickerManager.sortingType.comparator must not be null

How can I fix that could you help me please?
Best regards.

**Comment by DroidNinja** [comment]
Try 2.2.3. Reopen if still happening
