### ISSUE TITLE
Tab names aren't visible

### ISSUE THREAD

**Issue by karuppiah7890** [DroidNinja/Android-FilePicker#22]
Hey! Thanks for making the Android-FilePicker. I used it for my Demo App for testing my module.

I was testing the Demo App in my Fire Tablet, which has Android 5.1. And I noticed that the tab names weren't shown for the document picker. I was able to swipe through the PDF and other tabs. But the names of the tabs weren't visible.

What is this bug ? I don't get it. And I haven't tried it on any other device, since I don't have any other than my Tablet

**Comment by DroidNinja** [comment]
not able to replicate on any other device. Please provide more details. What code are you using?

**Comment by karuppiah7890** [comment]
I used the code in your examples. And it worked on other phones, but not my tablet. No idea why

**Comment by DroidNinja** [comment]
Closing due to not able replicate. Reopen this, if someone else has this same problem.
