### ISSUE TITLE
error: cannot access Fragment class file for androidx.fragment.app.Fragment not found

### ISSUE THREAD

**Issue by CodeDakait** [DroidNinja/Android-FilePicker#222]
I find this error during use of the Android-Filepicker

**Comment by NiravPotenza** [comment]
getting same issue but is there any way to implement without androidx..?

**Comment by nathansdev** [comment]
anybody found a solution for this?
I am getting this error when I use the latest version 2.2.1
"error: cannot access Fragment
class file for androidx.fragment.app.Fragment not found"

**Comment by HBiSoft** [comment]
You have two options to fix this:<br><br>1. Migrate your application to AndroidX (Refactor - Migrate to AndroidX)
2. Edit the library so it no longer uses AndroidX

**Comment by DroidNinja** [comment]
> You have two options to fix this:
> 
> 1. Migrate your application to AndroidX (Refactor - Migrate to AndroidX)
> 2. Edit the library so it no longer uses AndroidX

Try above solution. Reopen if still happening
