### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [DroidNinja/Android-FilePicker#224]
![image](https://user-images.githubusercontent.com/15881869/56568856-70290580-65ea-11e9-8818-5cb7f29cf20b.png)

**Comment by smedic** [comment]
https://stackoverflow.com/a/43944280/1374065 check this

**Comment by rajextreme9476** [comment]
Add plugin in gradle
        compile "org.jetbrains.kotlin:kotlin-stdlib:1.3.31"

**Comment by lubritto** [comment]
Just to be updated, add to the build.gradle depedencies:

```
implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.31'
```

**Comment by DroidNinja** [comment]
Reopen if still happening

**Comment by adityapise** [comment]
> 
> 
> Reopen if still happening

Yes Please check Issue 274
