### ISSUE TITLE
Not able to inflate menu options

### ISSUE THREAD

**Issue by AslanDevbrat** [DroidNinja/Android-FilePicker#226]
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <item
        android:id="@+id/action_open"
        android:title="Fragment Activity"
        app:showAsAction="always" />
</menu>

 @Override
  public boolean onCreateOptionsMenu(Menu menu) {

    MenuInflater inflater = getMenuInflater();

    inflater.inflate(R.menu.main_menu, menu);

    return true;

  }

**Comment by DroidNinja** [comment]
Please provide more details.

**Comment by DroidNinja** [comment]
Reopen if still happening
