### ISSUE TITLE
You can mark more than 1 picture, when maxCount is 1

### ISSUE THREAD

**Issue by nikoloz14** [DroidNinja/Android-FilePicker#23]

**Comment by DroidNinja** [comment]
Could you please describe what code are you using? because I can't seem to replicate this.

**Comment by nikoloz14** [comment]
FilePickerBuilder.getInstance().setMaxCount(1)
                .setActivityTheme(R.style.AppTheme_ActionBar)
                .pickPhoto(this);

It picks 1 photo, though you can mark more then 1, but only if u press on checbox. If you press picture, there is no problem, only on checkbox

**Comment by DroidNinja** [comment]
fixed in latest build. Please check and confirm. Thanks.
