### ISSUE TITLE
2.1.5版 NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;

### ISSUE THREAD

**Issue by parsebobo** [DroidNinja/Android-FilePicker#231]
2.1.5版找找不到这个addOnTabSelectedListener：NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;

**Comment by parsebobo** [comment]
已解决这个问题

**Comment by sivabe35** [comment]
如何解决这个问题呢

**Comment by dphans** [comment]
库在最新版本（2.2.1）中仍然出现此问题。

**Comment by sivabe35** [comment]
[Implemented addOnTabSelectedListener instead of setOnTabSelectedListener in TabLayoutHelper class](https://github.com/DroidNinja/Android-FilePicker/pull/233)

**Comment by chumendaiyibeigouqi** [comment]
我遇到了这个问题，但是解决了，遇到问题的环境是 compileSdkVersion 28  targetSdkVersion 28，我把28 改成了 27，并且把 appcompat-v7、design 都换成了 27.1.1，这样这个问题就不会出现了，但是我不能适配刘海屏了

**Comment by parsebobo** [comment]
design 换成27.1.1 就可以了

**Comment by DroidNinja** [comment]
Please migrate to androidx asap.

**Comment by muyoumingzi** [comment]
我的是项目的Tablayout和这个库的Tablayout版本不一致导致的，尝试一下这个，在项目的app下的gradle文件中加上 configurations.all {
    resolutionStrategy {
        force 'com.google.android.material:material:1.1.0'//强行指定为这个文件选择库所用的material版本
    }
}
这段是和dependencies{}平级的
