### ISSUE TITLE
Not working in Android 10

### ISSUE THREAD

**Issue by lakshyapunhani** [DroidNinja/Android-FilePicker#236]

**Comment by dphans** [comment]
Please details the issue, I'm using Android 10 and it working well (I'm not author this library).

**Comment by SunTaolin** [comment]
I think it doesn't work in targetSdkversion 29, because getExternalStorageDirectory() was deprecated in target29 Android Q

**Comment by tjdam007** [comment]
As Android 10 has restricted the use of External Storage.
But they also provided the legacy support, you can use 
android:requestLegacyExternalStorage="true"

**Comment by pouriabagheri** [comment]
any thought of updating the library to support the android 10 without `android:requestLegacyExternalStorage="true"` as of android 11 this solution would no longer work

**Comment by rituapplocum** [comment]
How to use the library in Android 11
