### ISSUE TITLE
It shows "No Files Found"

### ISSUE THREAD

**Issue by sagar091** [DroidNinja/Android-FilePicker#241]
I have tried everything as per the example given and also look into its original source code. But it didn't show me any single file. I have too many files in storage.

**Manifest provider**
`<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.coders"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>`

**file_paths**
`<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
</paths>`

**Picker Code**
`Functions.setPermission(context, arrayOf(
		FilePickerConst.PERMISSIONS_FILE_PICKER), object: PermissionListener {
	override fun onPermissionGranted() {
		FilePickerBuilder.Companion.instance
		.enableDocSupport(true)
		.pickFile(context as Activity)
	}
	override fun onPermissionDenied(deniedPermissions: List < String > ) {}
})
`

Tell me if I am missing something to implement this. **Urgent**

**Comment by omarhaj007** [comment]
same problem I have and I have tried everything as per the example given but the same result "No Files Found"

**Comment by Fahmy07** [comment]
Same problem here all the tabs show "No FIles Found" - OnePlus 7 Pro (Android 10) 😐

**Comment by sagar091** [comment]
I found the solution. It works for me:
Add this line in your manifest's <application> tag
`android:requestLegacyExternalStorage="true"`

This is used to access storage for android 10

**Comment by Fahmy07** [comment]
Thank you, I just fixed the issue with the same solution.

**Comment by liyuhaolol** [comment]
> I found the solution. It works for me:
> Add this line in your manifest's tag
> `android:requestLegacyExternalStorage="true"`
> 
> This is used to access storage for android 10

but this is a temporary solution

**Comment by DroidNinja** [comment]
Try 2.2.2
