### ISSUE TITLE
Images not showing on android 10

### ISSUE THREAD

**Issue by Dhana2513** [DroidNinja/Android-FilePicker#242]

**Comment by Priyadarshni24** [comment]
Hi,
I am also dealing with the same issue. 
This only happens in android 10.

Kindly suggest the solution which is very much required.

Thanks in advance.

**Comment by Dhana2513** [comment]
just add 

        android:requestLegacyExternalStorage="true"
in your application tag

```
<application
        android:requestLegacyExternalStorage="true"
       >
```

**Comment by perez-alex** [comment]
> I found the solution of this problem
> add android:requestLegacyExternalStorage="true"
> in your manifest
> 
> ```
> <application
>         android:requestLegacyExternalStorage="true"
>        >
> ```

This is only a temporary fix, in order to keep this library working in the future you need to implement Scoped Storage to access the files

eg: https://heartbeat.fritz.ai/implementing-scoped-storage-in-android-10-4b657280c066

**Comment by liyuhaolol** [comment]
> > I found the solution of this problem
> > add android:requestLegacyExternalStorage="true"
> > in your manifest
> > ```
> > <application
> >         android:requestLegacyExternalStorage="true"
> >        >
> > ```
> 
> This is only a temporary fix, in order to keep this library working in the future you need to implement Scoped Storage to access the files
> 
> eg: https://heartbeat.fritz.ai/implementing-scoped-storage-in-android-10-4b657280c066

in Android 10,if you create a file in /storage/emulated/0/Documents,then process ContentResolver.delete(),to delete file. you will find the file still there,i don't know why. then use you blog method can't query that file. in targetSdkVersion 29,but still can query it in targetSdkVersion 28, Very confused.

**Comment by DroidNinja** [comment]
Try 2.2.2 now.
