### ISSUE TITLE
Didn't find class "kotlinx.coroutines.Dispatchers"

### ISSUE THREAD

**Issue by nguyencongbinh** [DroidNinja/Android-FilePicker#247]
I just update version to 2.2.2 to let this library work with Android 10.

**1. For Document Picker:** 
    it worked
**2. For Image Picker:**
 App crash with `"Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.Dispatchers" `

![image](https://user-images.githubusercontent.com/14269299/77871804-6b93b500-726f-11ea-826d-70c9ecb3d446.png)

**Comment by adityapise** [comment]
Reason for bug and , solution please
