### ISSUE TITLE
Toolbar options not visible

### ISSUE THREAD

**Issue by hrsalehi** [DroidNinja/Android-FilePicker#25]
My app theme is ```Theme.AppCompat.Light.NoActionBar``` and by this theme ,the picker toolbar items such as back button, title and done button is not visible. But when I set a specific theme for file picker such as ```Theme.AppCompat.Light.DarkActionBar``` my main toolbar is visible below the theme toolbar.

![screenshot_20161113-123803](https://cloud.githubusercontent.com/assets/6253428/20244618/5e6d5482-a99e-11e6-8947-a2a381a6d724.jpg)

another issue is I want to change the toolbar title and done button texts.

**Comment by DroidNinja** [comment]
Inherit the default _LibApptheme_  and set your colors for theming filepicker.
