### ISSUE TITLE
addFileSupport nothing found

### ISSUE THREAD

**Issue by heyingjie** [DroidNinja/Android-FilePicker#250]
current version:
implementation 'com.droidninja:filepicker:2.2.2'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.5'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5'

code as below:
String audioTypes[] = {".mp3", ".aac"};
FilePickerBuilder.getInstance().setMaxCount(10)
                        .setActivityTheme(R.style.LibAppTheme)
                        .showFolderView(true)
                        .enableDocSupport(true)
                        .addFileSupport("Audio", audioTypes, R.drawable.ic_music_circle_color)
                        .pickFile(getActivity());

result is nothing found,is there any problem?

**Comment by heyingjie** [comment]
remove dot before suffix,everything ok.please update doc.

**Comment by DroidNinja** [comment]
done
