### ISSUE TITLE
TransactionTooLargeException at MediaFolderPickerFragment

### ISSUE THREAD

**Issue by yamifr07** [DroidNinja/Android-FilePicker#251]
When selecting a folder in the file picker I'm getting

java.lang.RuntimeException: Failure from system
TransactionTooLargeException at MediaFolderPickerFragment.kt:170

FilePicker 2.2.2
Glide 4.11.0
compileSdkVersion 29

**Comment by DroidNinja** [comment]
Can you tell me how many files are there in the particular folder ?

**Comment by yamifr07** [comment]
More than 500. But Android can carry no more than 1MB of data. So it's easy to get that exception.

**Comment by DroidNinja** [comment]
Fixed in 2.2.4. Please check
