### ISSUE TITLE
setSelectedFiles error

### ISSUE THREAD

**Issue by hamaz562006** [DroidNinja/Android-FilePicker#261]
setSelectedFiles requires filePaths
from where i get file paths 

in androidx  java

compileSdkVersion 28
targetSdkVersion 28

java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

**Comment by br-neeraj** [comment]
enable multidex to solve this problm

**Comment by DroidNinja** [comment]
setSelectedFiles requires the uri list of already selected items which you get in onActivityResult.
Also, as @br-neeraj if you are getting 
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

try enabling multidex
