### ISSUE TITLE
Caused by android.os.TransactionTooLargeException: data parcel size 1813608 bytes

### ISSUE THREAD

**Issue by hassan4000** [DroidNinja/Android-FilePicker#263]
i used filepicker to open gallery and select some photo
when i open gallery i face this problem 
TransactionTooLargeException: data parcel size 1813608 bytes
i don't know why that happen 
can anyone help me?

**Comment by dikhawk** [comment]
that's happens because user have many photos in folder, author transmits through Bundle args, but bundle have limits.

**Comment by dikhawk** [comment]
override fun onFolderClicked(photoDirectory: PhotoDirectory) {
        val intent = Intent(activity, MediaDetailsActivity::class.java)
        **intent.putExtra(PhotoDirectory::class.java.simpleName, photoDirectory)**
        intent.putExtra(FilePickerConst.EXTRA_FILE_TYPE, fileType)
        activity?.startActivityForResult(intent, FilePickerConst.REQUEST_CODE_MEDIA_DETAIL)
    }

that's happen error

**Comment by dikhawk** [comment]
```
how fix: in MediaFolderPickerFragment.kt
    override fun onFolderClicked(photoDirectory: PhotoDirectory) {
        val intent = Intent(activity, MediaDetailsActivity::class.java)
        photoDirectory.medias.clear()
        intent.putExtra(PhotoDirectory::class.java.simpleName, photoDirectory)
        intent.putExtra(FilePickerConst.EXTRA_FILE_TYPE, fileType)
        activity?.startActivityForResult(intent, FilePickerConst.REQUEST_CODE_MEDIA_DETAIL)
    }
```
add  **photoDirectory.medias.clear()**

**Comment by hassan4000** [comment]
thanks a lot for your help
The problem has been successfully resolved.
please update the  library to fix this problem for all  developers.

**Comment by LZG10** [comment]
Hi @hassan4000, could you share on how to edit the kt file (Read only)? Thus I imported the library using folder instead of dependencies but then it failed to resolve with some errors.
