### ISSUE TITLE
AAPT: error: style attribute 'attr/tabBackground not found

### ISSUE THREAD

**Issue by abiemann** [DroidNinja/Android-FilePicker#269]
using 2.2.4

there's 3 of these "Android resource linking failed" errors that fail building:

AAPT: error: style attribute 'attr/tabBackground
AAPT: error: style attribute 'attr/tabGravity
AAPT: error: style attribute 'attr/tabMaxWidth

**Comment by engineer1109** [comment]
me too

**Comment by ramu2514** [comment]
Add to dependencies

    implementation "com.google.android.material:material:1.1.0"

**Comment by chj233** [comment]
me too

**Comment by chj233** [comment]
> 添加到依赖项
> 
> ```
> implementation "com.google.android.material:material:1.1.0"
> ```

Thank you very much.
