### ISSUE TITLE
Need improve when setMaxtCount is 1

### ISSUE THREAD

**Issue by nguyencongbinh** [DroidNinja/Android-FilePicker#27]
When I pick a photo and set maxCount is 1, then I touch to select a photo. And if I want to change select photo, I need to uncheck the photo I checked before first. It should automatically uncheck the old one and select new one. Hope you fix this issue.

**Comment by DroidNinja** [comment]
fixed in latest build.

**Comment by nguyencongbinh** [comment]
When you release new version ?

**Comment by DroidNinja** [comment]
latest build already uploaded. **(1.0.7)** . Just updated readme file.
