### ISSUE TITLE
How to check mimeType

### ISSUE THREAD

**Issue by MustafaDev-shaikh** [DroidNinja/Android-FilePicker#271]
I need to check mimeType after selecting image and PDF file how do I check that is any key like getMimeType will be more helpfull

**Comment by DroidNinja** [comment]
No, it only returns Uri for the file selected. However, I will suggest now to use Android storage framework for File picker as Filepicker will not work from Android 11.

**Comment by MustafaDev-shaikh** [comment]
Your not going to update this library anymore for android 11
