### ISSUE TITLE
I can't get location information when I use Android 10 mobile phone to take photos

### ISSUE THREAD

**Issue by myself1002** [DroidNinja/Android-FilePicker#276]
I can't get location information when I use Android 10  mobile phone to take photos

**Comment by DroidNinja** [comment]
That is not the library problem. You need location permission in your app as this module doesn't handle media capture. It uses device default camera.

**Comment by myself1002** [comment]
Other mobile phones can turn on location, but Android 10 can't, and has obtained location permission. If uses device default camera，I can get the location
