### ISSUE TITLE
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;

### ISSUE THREAD

**Issue by daytionsiddharth18** [DroidNinja/Android-FilePicker#282]

**Comment by zaaach** [comment]
I got the same error...

**Comment by JewelKing** [comment]
> No description provided.

You do not import kotlin setting.
first you need to import Colin,  then there has a issue.
add
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.5'
it's will ok.

**Comment by zaaach** [comment]
@JewelKing Thanks!

**Comment by JewelKing** [comment]
@zaaach That's all right.

**Comment by tirumala007** [comment]
same error, worked. how can i get uri from activity result ?

**Comment by premeditate** [comment]
> > 没有提供说明。
> 
> 您不导入 kotlin 设置。
> 首先你需要导入 Colin，然后有一个问题。
> 添加
> 实现 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5'
> 实现 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.5'
> 就可以了。

what?
