### ISSUE TITLE
Idea to add File size

### ISSUE THREAD

**Issue by Rajnish23** [DroidNinja/Android-FilePicker#285]
Hi @DroidNinja 
I am using this library in one of my projects for Media and Other type of file. In our project we have a restriction for selecting file which is greater than 10 MB for Image and for Video we have size as well as Duration restriction. 
As of now I am looping through all the file paths checking the file size and showing pop up if not matching the constraint.

### Here is my suggestion, 
1. Either we can add the opacity to the item whose file size is less than the provided size and does not let them to select the file.
2. We can add the  `MediaStore.Images.Media.SIZE` and `MediaStore.Video.Media.SIZE` in the projection array and pass it to query.

### Example
```
//For Images
 String[] projection = new String[] {
            MediaStore.Images.Media._ID,
            MediaStore.Images.Media.DISPLAY_NAME,
            MediaStore.Images.Media.SIZE
    };

//For Videos
  String[] projection = new String[] {
            MediaStore.Video.Media._ID,
            MediaStore.Video.Media.DISPLAY_NAME,
            MediaStore.Video.Media.DURATION,
            MediaStore.Video.Media.SIZE
    };
```

Let me know, I am interested in adding this feature.

**Comment by Rajnish23** [comment]
Hey, Should I work on this feature enhancement?

**Comment by DroidNinja** [comment]
sure...it will be great add. Please raise a PR. Happy to review and merge it

**Comment by Rajnish23** [comment]
Hi @DroidNinja 
How about an Idea of adding a different file size for Images, Videos and Docs?

**Comment by DroidNinja** [comment]
DocPicker will not work in Android 11 sadly. It will open native file picker for Android 11. I will automatically add check for this in next release.

For image/videos, we can add size limit separately.

**Comment by Rajnish23** [comment]
Okay, I'll Remove the file size support for DocPicker and update the PR .
