### ISSUE TITLE
showFolderView not working

### ISSUE THREAD

**Issue by saqibsoftwares** [DroidNinja/Android-FilePicker#289]
Hello,
Thank you for this amazing library. I'm trying to set folder view when selecting custom files but it is not working.

`implementation 'com.droidninja:filepicker:2.2.4'` 

`String[] types = new String[]{"MP3"};
FilePickerBuilder.getInstance().setMaxCount(500).showFolderView(true).setActivityTitle("Select Audio Clips").addFileSupport("MP3 File", types).enableImagePicker(false).enableCameraSupport(false).enableDocSupport(false).enableVideoPicker(false).pickFile(this, 2);
`

![image](https://user-images.githubusercontent.com/11803610/90960804-aec02000-e4bd-11ea-8245-5caeb4d228bb.png)

**Comment by DroidNinja** [comment]
Folder view is only supported in image picker. Not for filepicker.
