### ISSUE TITLE
WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by Rajnish23** [DroidNinja/Android-FilePicker#296]
If app targets Android 11, both the `WRITE_EXTERNAL_STORAGE` permission no longer provide any additional access.

Recommend defining `maxSdkVersion="28"` in `AndroidManifest.xml`

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28"/>`

**Comment by DroidNinja** [comment]
Removing the permission as it is not required.
