### ISSUE TITLE
can select other type File？

### ISSUE THREAD

**Issue by 18633847058** [DroidNinja/Android-FilePicker#30]
can custom type of file？
how to set the type？

**Comment by fast1234** [comment]
I also want to customize it to choose for other type of files as well. Also can we show photos and files by click of one button. I mean to merge the two button functionality. Any help will be highly appreciated

**Comment by DroidNinja** [comment]
No, currently It does not support custom type. I will probably implement this in next release.

**Comment by DroidNinja** [comment]
done

**Comment by behelit** [comment]
Can you explain how to do this?
