### ISSUE TITLE
When there is a new file in the phone storage, the acquisition list does not contain~

### ISSUE THREAD

**Issue by design365** [DroidNinja/Android-FilePicker#301]
First of all, thank you for this open source project. The following problems occurred during use:
For example, there is an additional .doc file in a directory of /sdcard/ in the mobile phone storage, but the file list obtained by this open source project does not include this file, and the files in the list are all very old. The new file seems to be different No real-time updates come in.
Please check this issue.

**Comment by DroidNinja** [comment]
This library is using Material Design 2.0 themes and widgets. Your app must have these dependencies to work with:
`com.google.android.material:material:1.1.0`
