### ISSUE TITLE
How to run your app?Not found files:CallerFragmentPermissionsDispatcher and MainActivityPermissionsDispatcher.

### ISSUE THREAD

**Issue by heweiquan1992** [DroidNinja/Android-FilePicker#31]
How can i find the files?(MainActivityPermissionsDispatcher/files:CallerFragmentPermissionsDispatcher )
![image](https://cloud.githubusercontent.com/assets/21353081/21603227/7eb8ff2e-d1d6-11e6-8617-4730287bb3db.png)

**Comment by invisible66** [comment]
how did you run app?
