### ISSUE TITLE
Camera is not working in Android Nougat 7.0

### ISSUE THREAD

**Issue by ravitejaaketi** [DroidNinja/Android-FilePicker#35]
Getting FileUriExposedException

**Comment by ravitejaaketi** [comment]
Working Solution for android nougat 7.0 :

------ Add provider in Manifest ----------
<application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true">
        <activity android:name=".FilePickerActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.DarkActionBar">
        </activity>

        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="droidninja.filepicker.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
    </application>

------- Add res\xml\ provider_paths --------
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
</paths>

------- Code Changes ----------
public Intent dispatchTakePictureIntent(Activity activity) throws IOException {
        Intent takePictureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        // Ensure that there's a camera activity to handle the intent
        if (takePictureIntent.resolveActivity(mContext.getPackageManager()) != null) {
            // Create the File where the photo should go
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                File newFile = createImageFile();
                takePictureIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                takePictureIntent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
                Uri photoURI = FileProvider.getUriForFile(activity, "droidninja.filepicker.provider", newFile);
                takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, photoURI);
            } else {
                takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, Uri.fromFile(createImageFile()));
            }
            return takePictureIntent;
        }
        return null;
    }

------- And inCreateImageFile() method ----------
       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            mCurrentPhotoPath = "file:" + image.getAbsolutePath();
        }else{
            mCurrentPhotoPath = image.getAbsolutePath();
        }

**Comment by DroidNinja** [comment]
fixed in latest build.

**Comment by ravitejaaketi** [comment]
ok.
