### ISSUE TITLE
FilePicker Changed my demo app's name

### ISSUE THREAD

**Issue by cuteyoko** [DroidNinja/Android-FilePicker#38]
after i add  `compile ...` to  "build.gradle" 

my demo app's name changed to "FilePicker" 
[when i debug it on my phone]

i know there's some conflects in res folder 

is it a bug or did i use it in a wrong way ?

**Comment by DroidNinja** [comment]
I do not think this is a bug. But has removed app_name completely from filepicker manifest file in the latest build. Please test and report if there is an issue.

**Comment by cuteyoko** [comment]
then its not a problem anymore & ty
