### ISSUE TITLE
Problem when set Max count is 1

### ISSUE THREAD

**Issue by nguyencongbinh** [DroidNinja/Android-FilePicker#39]
At version 1.0.7, when setMaxCount(1), it auto back to the activity when pick an image ( no need to click "Done"), but latest version (2.0.0), the issue is happened. Please make the behavior like old version. Thank you

**Comment by nguyencongbinh** [comment]
Hi ,
Please have a look on this issue. Thank you.

**Comment by DroidNinja** [comment]
Try 2.0.1 version and close issue if fixed. Thanks for filing these bugs. :)
