### ISSUE TITLE
onActivityResult is never called on the Fragment when the chooser is activated from a fragment

### ISSUE THREAD

**Issue by s-madushan** [DroidNinja/Android-FilePicker#4]
In order to `onActivityResult` be called on the fragment, `startActivityForResult` should be called from the fragment (as far as I know). However, the library calls the `startActivityForResult` on behalf of the application in `FilePickerBuilder`

> ```
private void start(Activity context)
>     {
>         Intent intent = new Intent(context, FilePickerActivity.class);
>         intent.putExtras(mPickerOptionsBundle);
>         context.startActivityForResult(intent,FilePickerConst.REQUEST_CODE);
>     }
````

It accepts a one parameter, `context` of type `Activity`. In order to call the method in a fragment, one would use `getActivity()` since it returns it's parent activity. But `startActivityForResult` is called on the activity rather than on the fragment. The fragment never receives the `onActivityResult` callback.

**Comment by DroidNinja** [comment]
Yes, you're right, there should be support for fragment too. I will add fragment support. Thanks for filing this issue.

**Comment by DroidNinja** [comment]
Hey @s-madushan  I have added support for fragment. Please checkout the latest build and confirm.
