### ISSUE TITLE
Folders called pdf/doc/ppt/txt will be showed on the file list

### ISSUE THREAD

**Issue by cuteyoko** [DroidNinja/Android-FilePicker#40]
this ↑

**Comment by DroidNinja** [comment]
which list? What have you used? please show some code.

**Comment by cuteyoko** [comment]
![this "doc" is a folder called "doc" in fact](https://github.com/cuteyoko/BeAStarter/blob/master/docfolder.png)

**Comment by DroidNinja** [comment]
Try 2.0.1 version and close issue if fixed. Thanks for filing these bugs. :)
