### ISSUE TITLE
Can't show custom file 

### ISSUE THREAD

**Issue by MrEngineer13** [DroidNinja/Android-FilePicker#45]
I want to show the tab for zip files but when I run this code I don't see them anywhere. I'm running version 2.2 of your library.

    String[] fileTypes = new String[]{".zip"};
            FilePickerBuilder.getInstance()
                    .addFileSupport("Zip", fileTypes)
                    .setMaxCount(5)
                 .setActivityTheme(android.support.v7.appcompat.R.style.Base_Theme_AppCompat_Light)
                    .setSelectedFiles(filePaths)
                    .enableDocSupport(true)
                    .pickFile(this);

**Comment by DroidNinja** [comment]
Did you try to run the sample?
