### ISSUE TITLE
Hide default tabs

### ISSUE THREAD

**Issue by MrEngineer13** [DroidNinja/Android-FilePicker#46]
I want to hide some default tabs on the document picker, like PPT, DOC, TXT. How would I do that?

**Comment by DroidNinja** [comment]
what custom tabs? If you want to add tabs for particular file types, use addFileSupport() method like this ( for zip support):

```
String[] zips = {".zip",".rar"};
 FilePickerBuilder.getInstance().setMaxCount(maxCount)
                    .setSelectedFiles(docPaths)
                    .setActivityTheme(R.style.FilePickerTheme)
                    .addFileSupport("ZIP",zips)
            .enableDocSupport(true) //if you want to hide default tabs for document
                    .pickFile(this);
```

**Comment by MrEngineer13** [comment]
When I try it that way and disable doc support I end up getting just a title bar and a blank screen. When I reenable the DocSupport I get the custom tab though

**Comment by DroidNinja** [comment]
Weird thing. App sample works as it should. When you disable default doc support, it will not add default tabs and only shows tabs that you added through `addFileSupport()` method

**Comment by MrEngineer13** [comment]
The problem was I didn't have the required permissions in my manifest:

  ` <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
  `  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

I would either detail what's going on with permissions and the PermissionsDispatcher or remove it entirely and just do an example with no other libraries

**Comment by MrEngineer13** [comment]
Also, since I was using regular fragments, I had to switch over to Support fragments because when I have ` .pickFile(this);` inside the fragment it works but  ` .pickFile(getActivity());` does not

**Comment by MrEngineer13** [comment]
And I noticed if you want to test and open the docs viewer and the photo viewer at the same time it doesn't work.

**Comment by DroidNinja** [comment]
What doesn't work?

**Comment by MrEngineer13** [comment]
The tabs, there aren't any and it's blank
