### ISSUE TITLE
LeakCanary reports a memory leak at FilePickerActivity

### ISSUE THREAD

**Issue by saltyx** [DroidNinja/Android-FilePicker#48]
The following is a detailed message

Android version 7.0

In com.shiyan.netdisk_android:1.0:1.
* droidninja.filepicker.FilePickerActivity has leaked:
* GC ROOT static droidninja.filepicker.PickerManager.ourInstance
* references droidninja.filepicker.PickerManager.pickerManagerListener
* leaks droidninja.filepicker.FilePickerActivity instance

* Retaining: 35 KB.
* Reference Key: a59d7d50-a8c1-4f9c-885f-72cf96a60d1b
* Device: samsung samsung SM-G9350 hero2qltezc
* Android Version: 7.0 API: 24 LeakCanary: 1.5 00f37f5
* Durations: watch=5026ms, gc=131ms, heap dump=2120ms, analysis=60082ms

* Details:
* Class droidninja.filepicker.PickerManager
|   static $classOverhead = byte[852]@319163393 (0x13060c01)
|   static ourInstance = droidninja.filepicker.PickerManager@319097872 (0x13050c10)
* Instance of droidninja.filepicker.PickerManager
|   static $classOverhead = byte[852]@319163393 (0x13060c01)
|   static ourInstance = droidninja.filepicker.PickerManager@319097872 (0x13050c10)
|   alreadySelectedFiles = null
|   currentCount = 0
|   docFiles = java.util.ArrayList@319149824 (0x1305d700)
|   docSupport = true
|   enableCamera = true
|   enableOrientation = false
|   fileTypes = java.util.ArrayList@319149848 (0x1305d718)
|   maxCount = 3
|   mediaFiles = java.util.ArrayList@319149800 (0x1305d6e8)
|   pickerManagerListener = droidninja.filepicker.FilePickerActivity@319243456 (0x130744c0)
|   providerAuthorities = java.lang.String@315786288 (0x12d28430)
|   showFolderView = true
|   showGif = false
|   showVideos = true
|   theme = 2131361960
|   shadow$_klass_ = droidninja.filepicker.PickerManager
|   shadow$_monitor_ = 0
* Instance of droidninja.filepicker.FilePickerActivity
|   static TAG = java.lang.String@319098768 (0x13050f90)
|   static $classOverhead = byte[4692]@319193089 (0x13068001)
|   type = 18
|   mDelegate = android.support.v7.app.AppCompatDelegateImplN@315482752 (0x12cde280)
|   mEatKeyUpEvent = false
|   mResources = null
|   mThemeId = 2131361960
|   mCreated = true
|   mFragments = android.support.v4.app.FragmentController@315157536 (0x12c8ec20)
|   mHandler = android.support.v4.app.FragmentActivity$1@320115104 (0x131491a0)
|   mNextCandidateRequestIndex = 0
|   mOptionsMenuInvalidated = false
|   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@315201136 (0x12c99670)
|   mReallyStopped = true
|   mRequestedPermissionsFromFragment = false
|   mResumed = false
|   mRetaining = false
|   mStopped = true
|   mStartedActivityFromFragment = false
|   mStartedIntentSenderFromFragment = false
|   mExtraDataMap = android.support.v4.util.SimpleArrayMap@315130664 (0x12c88328)
|   mActionBar = null
|   mActionModeTypeStarting = 0
|   mActivityInfo = android.content.pm.ActivityInfo@315787872 (0x12d28a60)
|   mActivityTransitionState = android.app.ActivityTransitionState@315056072 (0x12c75fc8)
|   mAppLockCheckRunnable = android.app.Activity$1@315157296 (0x12c8eb30)
|   mAppLockIsInMultiWindowMode = false
|   mApplication = com.shiyan.netdisk_android.SecuDiskApplication@315811552 (0x12d2e6e0)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mComponent = android.content.ComponentName@315383776 (0x12cc5fe0)
|   mConfigChangeFlags = 0
|   mCurrentConfig = android.content.res.Configuration@315402968 (0x12ccaad8)
|   mDecor = null
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEatKeyUpEvent = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1883687040 (0x7046c880)
|   mExitTransitionListener = android.app.SharedElementCallback$1@1883687040 (0x7046c880)
|   mFinished = true
|   mFlipfont = 0
|   mFragments = android.app.FragmentController@315157152 (0x12c8eaa0)
|   mHandler = android.os.Handler@320115040 (0x13149160)
|   mHasCurrentPermissionsRequest = false
|   mIdent = 138615481
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@315157184 (0x12c8eac0)
|   mInstrumentation = android.app.Instrumentation@315596512 (0x12cf9ee0)
|   mIntent = android.content.I

ntent@315445952 (0x12cd52c0)
|   mLastNonConfigurationInstances = null
|   mMainThread = android.app.ActivityThread@315618048 (0x12cff300)
|   mManagedCursors = java.util.ArrayList@315130688 (0x12c88340)
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mPolicyManager = android.net.NetworkPolicyManager@315157824 (0x12c8ed40)
|   mReferrer = java.lang.String@315083720 (0x12c7cbc8)
|   mResultCode = 0
|   mResultData = null
|   mResumed = false
|   mScreenChangeListener = null
|   mSearchEvent = null
|   mSearchManager = null
|   mStartedActivity = false
|   mStopped = true
|   mTaskDescription = android.app.ActivityManager$TaskDescription@320115072 (0x13149180)
|   mTemporaryPause = false
|   mTitle = java.lang.String@316482016 (0x12dd21e0)
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@315183040 (0x12c94fc0)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1991870256 (0x76b98730)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.PhoneWindow@319550960 (0x130bf5f0)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@315203152 (0x12c99e50)
|   mInflater = com.android.internal.policy.PhoneLayoutInflater@314614928 (0x12c0a490)
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources@315386624 (0x12cc6b00)
|   mTheme = android.content.res.Resources$Theme@315158256 (0x12c8eef0)
|   mThemeResource = 2131361960
|   mBase = android.app.ContextImpl@315481552 (0x12cdddd0)
|   shadow$_klass_ = droidninja.filepicker.FilePickerActivity
|   shadow$_monitor_ = 1073742660
* Excluded Refs:
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by DroidNinja** [comment]
fixed in latest build. Please confirm and close bug. Thanks.
