### ISSUE TITLE
'addVideoPicker' method should get boolean to enable or disable.

### ISSUE THREAD

**Issue by glidodroid** [DroidNinja/Android-FilePicker#49]
Problem exactly is when we call FilePickerBuilder with ```addVideoPicker``` included for the first time in the app and then in some part of application I don't need video tab. In such case I don't have that option to disable where the video tab continuously shown since I initialised ```addVideoPicker``` first time in the app using getInstance.

**Comment by DroidNinja** [comment]
Thanks for the suggestion. Its done in latest build. Check it out.
