### ISSUE TITLE
FilePicker can't find the .docx file and .xlsx file

### ISSUE THREAD

**Issue by luyun181** [DroidNinja/Android-FilePicker#5]

**Comment by DroidNinja** [comment]
hey @luyun181 This library basically queries MediaStore database provided by android. I have tried replicating this bug on Nexus 5X(6.0) genymotion emulator. It couldn't able to get updates from mediastore database, if you inserted the document file recently in your storage. But When i restarted my emulator, I am able to see all types of document. I dont have Nexus device. Could you please replicate this scenario on actual device?
