### ISSUE TITLE
.showGifs(false) not working

### ISSUE THREAD

**Issue by mansukhgagal** [DroidNinja/Android-FilePicker#50]
FilePickerBuilder.getInstance().setMaxCount(maxCount)
                    .setSelectedFiles(photoPaths)
                    .setActivityTheme(R.style.FilePickerTheme)
                    .addVideoPicker()
            .enableCameraSupport(true)
            .showGifs(false)
            .showFolderView(true)
                    .pickPhoto(this);

When i pick image and set .showGifs(false) but gif files show in picker unable to avoid gif files

**Comment by DroidNinja** [comment]
fixed in latest build. Please confirm and close bug. Thanks.
