### ISSUE TITLE
setMaxCount crashes when set to 1

### ISSUE THREAD

**Issue by BSharp94** [DroidNinja/Android-FilePicker#51]
Attempting to limit the max selection to one. I attached the stack trace error

[FilePickerErrorST.txt](https://github.com/DroidNinja/Android-FilePicker/files/910482/FilePickerErrorST.txt)

**Comment by meet2011** [comment]
@DroidNinja Yes, I'm also facing same crash issue when setMaxCount set to 1 in ver 2.0.3

**Comment by lufuqiang** [comment]
@DroidNinja has same crash issue

**Comment by DroidNinja** [comment]
fixed in latest build. Please confirm and close bug. Thanks.
