### ISSUE TITLE
Multiple File Providers

### ISSUE THREAD

**Issue by ferleal** [DroidNinja/Android-FilePicker#52]
The Library should  leverage an empty subclass of the FileProvider to prevent merge Conflicts with your own File Providers at your Manifest
see [https://stackoverflow.com/questions/42893846/androidmanifest-merge-error-using-fileprovider](url)

**Comment by MegaThorx** [comment]
Same problem here

**Comment by Emeritus-DarranKelinske** [comment]
+1

**Comment by DroidNinja** [comment]
fixed in 2.0.5. Thanks for reporting.
