### ISSUE TITLE
Android 6.0 can not find doc

### ISSUE THREAD

**Issue by jmsodlier** [DroidNinja/Android-FilePicker#6]
my phone is nexus 5  with Android 6.0 os 
i tried but can not find any doc.

**Comment by DroidNinja** [comment]
This library basically queries MediaStore database provided by android. I have tried replicating this bug on Nexus 5X(6.0) genymotion emulator. It couldn't able to get updates from mediastore database, if you inserted the document file recently in your storage. But When i restarted my emulator, I am able to see all types of document. I dont have Nexus device. Could you please replicate this scenario on actual device?

**Comment by jmsodlier** [comment]
http://www.17sysj.com/video/lpds_5c7445955656a
this is the video

**Comment by jmsodlier** [comment]
I try on another phone with 6.0 os，worked well.
jmsoldier.xi@gmail.com that`s my email,
I want to make friend with you

**Comment by DroidNinja** [comment]
Yeah sure...you can contact me at : arun2007ind@gmail.com :)
