### ISSUE TITLE
LeakCanary detects memory leak

### ISSUE THREAD

**Issue by mithunraman** [DroidNinja/Android-FilePicker#60]
Hi,

LeakCanary reports leaks. Please find the log below.

* droidninja.filepicker.FilePickerActivity has leaked:
* GC ROOT static droidninja.filepicker.PickerManager.ourInstance
* references droidninja.filepicker.PickerManager.pickerManagerListener
* leaks droidninja.filepicker.FilePickerActivity instance

* Retaining: 687KB.
* Reference Key: fb2a2d81-b2dc-4167-b337-cfe2e2bf032c
* Device: asus asus ASUS_T00J WW_a501cg
* Android Version: 4.4.2 API: 19 LeakCanary: 1.5 00f37f5
* Durations: watch=15273ms, gc=166ms, heap dump=823ms, analysis=40239ms

Thanks,

**Comment by DroidNinja** [comment]
fixed in latest build. Please confirm and close bug. Thanks.
