### ISSUE TITLE
NPE in FilePickerActivity

### ISSUE THREAD

**Issue by josedlpozo** [DroidNinja/Android-FilePicker#65]
Hi guy!
I have realized that if you set maxItemCount to one, your library got a NullPointerException. The problem is in the method openSpecificFragment when the ArrayList that comes as a parameter is null.

I will open you a PR tomorrow 😄 

Thank u!

**Comment by josedlpozo** [comment]
I have detected that this happens when the user don't add the selected files arraylist to the FilePickerBuilder.

**Comment by DroidNinja** [comment]
fixed in 2.0.5. Thanks for the contribution.
