### ISSUE TITLE
Can't open Office file.

### ISSUE THREAD

**Issue by tianshaokai** [DroidNinja/Android-FilePicker#7]

**Comment by DroidNinja** [comment]
@tianshaokai What do you mean?

**Comment by tianshaokai** [comment]
I want to preview Office files on Android.

**Comment by DroidNinja** [comment]
Which device you are using? This library only displays docx,doc,ppt,pptx,xls,xlsx office files. If there's problem, please show something atleast?

**Comment by tianshaokai** [comment]
XiaoMi 2s  is my device. I want to see the contents of the selected office file. This library can‘t support.

**Comment by DroidNinja** [comment]
@tianshaokai This library is just a picker through which you can select your document and return its path. It can't read the contents of documents and that is altogether different functionality.

**Comment by tianshaokai** [comment]
OK, Thanks .
