### ISSUE TITLE
number of selected files not updated

### ISSUE THREAD

**Issue by martialowt** [DroidNinja/Android-FilePicker#70]
Hi,

when we select files from a folder and go back to list of folders, the title in actionbar is not updated with the total number of selected files...  
I have always 0/10

but when i clicked on "done", it's ok, files are  present in the onActivityResult()

**Comment by DroidNinja** [comment]
fixed in 2.0.6. Thanks for reporting.

**Comment by martialowt** [comment]
Hi, it's ok... Thanks
