### ISSUE TITLE
How to override the bar title "attachments" & "done"

### ISSUE THREAD

**Issue by zyw745293** [DroidNinja/Android-FilePicker#71]
I want to replace the filepicker's title with custom words, How should I do？ By the way, can you make the filepicker to select files by retrieve phone directory directly?  This will be convenient for other users.

**Comment by NoNews** [comment]
@zyw745293 
For replace title  just create string resources with the same names as  in library:

```
<string name="done">Done</string>
<string name="attachments_title_text" formatted="false">Attachments (%d/%d)</string>
```
