### ISSUE TITLE
Only landscape orientation

### ISSUE THREAD

**Issue by NoNews** [DroidNinja/Android-FilePicker#72]
Hi, Is it possible to consolidate the orientation to only landscape or portait programmatically? (Without overriding classes)

Faced with that trouble after screen orientation chage:

<img width="1152" alt="bug" src="https://user-images.githubusercontent.com/18613737/27736211-e4d995fa-5dab-11e7-8195-ea1f46cbd4bc.png">

Lollipop tablet.

**Comment by NoNews** [comment]
https://github.com/DroidNinja/Android-FilePicker/pull/73

So far it has not been possible to fix the bug, but I add orientation settings.

**Comment by NoNews** [comment]
@DroidNinja what about this issue and PR?

**Comment by DroidNinja** [comment]
Thanks for the PR. I will review and merge this weekend. Sorry for the delay. :/

**Comment by DroidNinja** [comment]
fixed in 2.0.7.
