### ISSUE TITLE
Attachments increases on device orientation change

### ISSUE THREAD

**Issue by mishu-bilfinger** [DroidNinja/Android-FilePicker#74]
If I set enableOrientation true , I found problem in attachments count when I change orientation. It happens when I send some setSelectedFiles. For example if I send setSelectedFiles 2 then each time I change orientation it increases the attachments by 2 like Attachments(2/x), (4/X), (6/X). For 3 it increases every time 3 and so on. please look after this issue. 

`FilePickerBuilder.getInstance().setMaxCount(100)
                .setSelectedFiles(filePaths) // contains some path
                .enableOrientation(true)
                .pickFile(this);`

**Comment by DroidNinja** [comment]
fixed in 2.0.7.
