### ISSUE TITLE
setMaxCount(1) use camera automatic select image

### ISSUE THREAD

**Issue by erdemtpz** [DroidNinja/Android-FilePicker#75]
FilePickerBuilder.getInstance().**setMaxCount(1)**
                            .setActivityTheme(R.style.AppTheme)
                            .pickPhoto(TabHomePageFragment.this);

The camera returns to the list after use. How to automatically restore the captured image instead

**Comment by DroidNinja** [comment]
fixed in 2.0.7.

**Comment by erdemtpz** [comment]
excellent. thank you
