### ISSUE TITLE
I want to get only video list 

### ISSUE THREAD

**Issue by imrananeuronsolutions** [DroidNinja/Android-FilePicker#78]
How can we get the list of only videos  for picking media not Both Images and Video both .?
Any Suggestion ?
Means i want to pick images and videos seperately .

**Comment by duyp** [comment]
I have same problem with @imrananeuronsolutions

**Comment by DroidNinja** [comment]
added option in 2.0.7. You can disable using `enableImagePicker(false)` method. Check out sample for more detail.

**Comment by imrananeuronsolutions** [comment]
Thanks for replying .. 

But As i try..    enableImagePicker(false) definition is not available in the class.

**Comment by DroidNinja** [comment]
Are you sure you are using 2.0.7?

**Comment by imrananeuronsolutions** [comment]
I am using ..Android Studio 2.3.2

**Comment by DroidNinja** [comment]
I am talking about this library version not studio version. Make sure you have latest version of this library i.e. 2.0.7
