### ISSUE TITLE
Audio Files Not Showing

### ISSUE THREAD

**Issue by nic003** [DroidNinja/Android-FilePicker#87]
Does audio files not supported? 

Thanks!

**Comment by DroidNinja** [comment]
Every file is supported if it exists in Android MediaStore database.

**Comment by nic003** [comment]
i use addFileSupport("Audio ", new String[]{".mp3"}); no result found,  given that i have multiple mp3 in my phone.

Thanks!

**Comment by DroidNinja** [comment]
It was a bug. It was reading files which are inserted as audio type in the database. Fixed in 2.0.8
