### ISSUE TITLE
tools not found in manifiest

### ISSUE THREAD

**Issue by pinvisible** [DroidNinja/Android-FilePicker#9]
Hello Team,

Library seems very nice. i am getting this error while working with Manifiest.

Error:The prefix "tools" for attribute "tools:replace" associated with an element type "application" is not bound.

**Comment by DroidNinja** [comment]
check out this link: http://stackoverflow.com/questions/32002361/how-to-fix-android-manifest-xml-naming-conflict

If resolved, please close the issue. Thanks!
