### ISSUE TITLE
About title suggestion

### ISSUE THREAD

**Issue by Ordosbxy** [DroidNinja/Android-FilePicker#90]
Thanks, nice library!  
Can we custome attachments_title_text?  Because in our app we just want FilePickedActivity named "%d/%d" or "Album (%d/%d)". In my app, we want it just named "%d/%d", but I don't know how to do it!

<string name="attachments_title_text" formatted="false">Attachments (%d/%d)</string>

**Comment by DroidNinja** [comment]
`<string name="attachments_title_text" formatted="false">Attachments (%d/%d)</string>`

override this string in your app string file.
