### ISSUE TITLE
How can we have Media picker and Doc picker in one Activity?

### ISSUE THREAD

**Issue by nimashahbazi90** [DroidNinja/Android-FilePicker#91]
Hi,
I was wondering if it is possible to have all file types (media, doc and etc) in one activity and navigate between them just using tabs. How can I manage to add this feature?

**Comment by DroidNinja** [comment]
Yes you can fork the library and merge both types of picker in one activity.

**Comment by andkishor** [comment]
Can you tell me the what changes i have to do?, I also want both files types in onACtivityReult() method
