### ISSUE TITLE
File icon image size on older devices.

### ISSUE THREAD

**Issue by nick-kleban** [DroidNinja/Android-FilePicker#92]
Seems like in document picker, in ImageView of list item, should have some scaleType like centerInside. 
On Samsung GT-I9100 (Android 4.1.2) if i set my own image to any of document file extension - the image don't have any padding and margins and lays on the bottom of list item. I'll soon add screenshot illustrating the issue.

**Comment by nick-kleban** [comment]
http://i67.tinypic.com/2hgftck.png

**Comment by nick-kleban** [comment]
[https://pasteboard.co/GH73lF3.png](url)

**Comment by nick-kleban** [comment]
[screenshot](https://pasteboard.co/GH73lF3.png)

**Comment by DroidNinja** [comment]
@nick-kleban Still happening in latest version?
