### ISSUE TITLE
FilePickerBuilder open for the first time without the toolbar

### ISSUE THREAD

**Issue by MohamedWael** [DroidNinja/Android-FilePicker#94]
File picker launches without the toolbar after accepting the storage permission for the first time 
Android version: 6, 7

**Comment by DroidNinja** [comment]
Have you specified toolbar theme for filepicker?

**Comment by MohamedWael** [comment]
Yes, here is my code

```java 
FilePickerBuilder.getInstance().setMaxCount(4)
                        .setActivityTheme(R.style.LibAppTheme)
                        .pickPhoto(view.getActivity()); 
```

**Comment by MohamedWael** [comment]
hay @DroidNinja !
still here ?

**Comment by DroidNinja** [comment]
@MohamedWael removed toolbar theme altogether. Now using dark actionbar theme. Just inherit LibAppTheme from filepicker and style it in your main module. See styling section in README
