### ISSUE TITLE
conflict with other library

### ISSUE THREAD

**Issue by waelsyrian996** [DroidNinja/Android-FilePicker#97]
when I added Android-FilePicker my project stopped from working 
compile 'com.github.bumptech.glide:glide:3.7.0'
all files for this library is not found anymore.

do you have any advise for this issue ?

**Comment by DroidNinja** [comment]
But this library do not use 3.7.0 glide version, its 4.0. Are you sure you are using correct version?

**Comment by DroidNinja** [comment]
closing bug due to inactivity
